export const TYPES = {
  USE_CASE_DECORATOR: Symbol.for('USE_CASE_DECORATOR'),
  LOGGER: Symbol.for('LOGGER'),
  STATE: Symbol.for('STATE'),
  WINDOW: Symbol.for('WINDOW'),
  STATE_MANAGER: Symbol.for('STATE_MANAGER'),
  BASE_STATE_MANAGER: Symbol.for('BASE_STATE_MANAGER'),
  APPLICATION: Symbol.for('APPLICATION'),
  VUE: Symbol.for('VUE'),
  ROUTER: Symbol.for('ROUTER'),
  RUNNER: Symbol.for('RUNNER'),
  LOGGER_LINK: Symbol.for('LOGGER_LINK'),
  EXECUTOR_LINK: Symbol.for('EXECUTOR_LINK'),
  SHOPPING_CART_REPOSITORY: Symbol.for('SHOPPING_CART_REPOSITORY'),
  GET_SHOPPING_CART: Symbol.for('GET_SHOPPING_CART'),
  CREATE_ARTICLE: Symbol.for('CREATE_ARTICLE'),
  REMOVE_ARTICLE: Symbol.for('REMOVE_ARTICLE')
}
